name = "WeakDepHelpers"
uuid = "7869a13a-7328-4bcf-a489-0f4bb64497c7"
version = "0.1.2"
authors = ["Stefan Krastanov <stefan@krastanov.org>"]

[weakdeps]
JuliaSyntaxHighlighting = "ac6e5ff7-fb65-4e79-a425-ec3bc9c03011"

[extensions]
WeakDepHelpersStyledStringsExt = ["JuliaSyntaxHighlighting"]

[compat]
JuliaSyntaxHighlighting = "1.12"
julia = "1.10"